### ISSUE TITLE
ipv6 support?

### ISSUE THREAD

**Issue by LsHallo** [karalabe/cloudflare-dyndns#3]
I would like an option to define specific records as AAAA and update them with the according ipv6 address. Would be nice if this could be added.
IPv6 Service could be: 
http://v6.ipv6-test.com/api/myip.php?json
https://v6.ident.me/
https://ifconfig.co/ (with -4 or -6 curl flag)

**Comment by ncruces** [comment]
I suggest using Cloudflare itself to get the IP (v6 and otherwise), like so:
https://github.com/ncruces/go-cloudflare/blob/678e8f5/dyndns/service.go#L148
